In [ ]:
import numpy as np

# Module 00: Stepping into Machine Learning

## Exercise 00: Matrix
### Partie sur les matrices

In [ ]:
from ex00.matrix import Matrix

# Instance
m1 = Matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(f"shape = {m1.shape}\n", m1)
m2 = Matrix([[0],[1],[2]])
print(f"shape = {m2.shape}\n", m2)
m3 = Matrix([[1, 2, 3, 11, 12, 13, 21, 22, 23, 31, 32, 33],[4, 5, 6, 14, 15, 16, 24, 25, 26, 34, 35, 36]])
print(f"shape = {m3.shape}\n", m3)

m4 = Matrix((1, 1))
print(f"shape = {m4.shape}\n", m4)
m5 = Matrix((2, 3))
print(f"shape = {m5.shape}\n", m5)
m6 = Matrix((1, 10))
print(f"shape = {m6.shape}\n", m6)
m7 = Matrix((10, 1))
print(f"shape = {m7.shape}\n", m7)

# Addition matrice avec matrice, float, str, tuple, list
m1 = Matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
m2 = Matrix([[9, 8, 7],[6, 5, 4],[3, 2, 1]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)

m1 = Matrix([[1],[4],[7]])
m2 = Matrix([[7],[5],[3]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)

m1 = Matrix([[1, 2, 3]])
m2 = Matrix([[3, 4, 5]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)

m1 = Matrix([[1]])
m2 = Matrix([[3]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)

m1 = Matrix([[1, 0, -5, 2, -8], [1, 0, -5, 2, -8]])
m2 = Matrix([[1.01, 0.8, -1.25, 2.5, -3.1], [3, -1.2, -2.5, 1, -4]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)


### Partie sur les vecteurs

In [ ]:
from ex00.matrix import Vector

# Instance
## Example 1
v1 = Vector([[1, 2, 3]])
print("## Example 1")
print(f"shape = {v1.shape}\n", v1)

## Example 2
v2 = Vector([[0],[1],[2]])
print("\n## Example 2")
print(f"shape = {v2.shape}\n", v2)

## Example 3
v3 = Vector([[1, 2, 3, 11, 12, 13, 21, 22, 23, 31, 32, 33]])
print("\n## Example 3")
print(f"shape = {v3.shape}\n", v3)

## Example 4
v4 = Vector((1, 1))
print("\n## Example 4")
print(f"shape = {v4.shape}\n", v4)

## Example 5
v5 = Vector((1, 2))
print("\n## Example 5")
print(f"shape = {v5.shape}\n", v5)

## Example 6
v6 = Vector((1, 10))
print("\n## Example 6")
print(f"shape = {v6.shape}\n", v6)

## Example 7
v7 = Vector((10, 1))
print("\n## Example 7")
print(f"shape = {v7.shape}\n", v7)

# Addition matrice avec matrice, float, str, tuple, list
## Example 8
v1 = Vector([[1, 2, 3]])
v2 = Vector([[9, 8, 7]])
print("\n## Example 8")
print(f"shape v1 + v2 = {(v1 + v2).shape}\n", v1 + v2)

## Example 9
v1 = Vector([[1],[4],[7]])
v2 = Vector([[7],[5],[3]])
print("\n## Example 9")
print(f"shape m1 + v2 = {(v1 + v2).shape}\n", v1 + v2)

## Example 10
v1 = Vector([[1]])
v2 = Vector([[3]])
print("\n## Example 10")
print(f"shape v1 - v2 = {(v1 - v2).shape}\n", v1 - v2)

## Example 11
v1 = Vector([[1, 2, 3]])
v2 = Vector([[3, 4, 5]])
print("\n## Example 11")
print(f"shape v1 - v2 = {(v1 - v2).shape}\n", v1 - v2)

## Example 12
v1 = Vector([[1],[4],[7]])
v2 = Vector([[7],[5],[3]])
print("\n## Example 12")
print(f"shape v1 - v2 = {(v1 - v2).shape}\n", v1 - v2)

## Example 13
v1 = Vector([[1]])
v2 = Vector([[3]])
print("\n## Example 13")
print(f"shape v1 - v2 = {(v1 - v2).shape}\n", v1 - v2)

In [ ]:
from ex00.matrix import Vector

## Example 13.right
v1 = Vector([[1, 0, -5, 2, -8]])
scalar = 0
print("\n## Example 13.right")
print(f"shape scalar * v1 = {(scalar * v1).shape}\n", scalar * v1)

## Example 13.left
v1 = Vector([[1, 0, -5, 2, -8]])
scalar = 0
print("\n## Example 13.left")
print(f"shape v1 * scalar = {(v1 * scalar).shape}\n", v1 * scalar)

## Example 14.right
v1 = Vector([[1, 0, -5, 2, -8]])
scalar = 3
print("\n## Example 14.right")
print(f"shape scalar * v1 = {(scalar * v1).shape}\n", scalar * v1)

## Example 14.left
v1 = Vector([[1, 0, -5, 2, -8]])
scalar = 3
print("\n## Example 14.left")
print(f"shape v1 * scalar = {(v1 * scalar).shape}\n", v1 * scalar)

## Example 15.right
v1 = Vector([[1, 0, -5, 2, -8]])
scalar = -0.5
print("\n## Example 15.right")
print(f"shape scalar * v1 = {(scalar * v1).shape}\n", scalar * v1)

## Example 15.left
v1 = Vector([[1, 0, -5, 2, -8]])
scalar = -0.5
print("\n## Example 15.left")
print(f"shape v1 * scalar = {(v1 * scalar).shape}\n", v1 * scalar)

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

## Example 16.right
v1 = Vector([[-5]])
scalar = 0
print("\n## Example 16.right")
print(f"shape scalar / v1 = {(scalar * v1).shape}\n", scalar / v1)

## Example 16.left
v1 = Vector([[1, 0, -5, 2, -8]])
scalar = 0
#scalar = 1
print("\n## Example 16.left")
print(f"shape v1 / scalar = {(v1 / scalar).shape}\n", v1 / scalar)

## Example 17.right
v1 = Vector([[1, 0, -5, 2, -8]])
#v1 = Vector([[-8]])
scalar = 2
print("\n## Example 17.right")
print(f"shape scalar / v1 = {(scalar / v1).shape}\n", scalar / v1)

## Example 17.left
v1 = Vector([[1, 0, -5, 2, -8]])
scalar = 2
print("\n## Example 17.left")
print(f"shape v1 / scalar = {(v1 / scalar).shape}\n", v1 / scalar)

## Example 18.right
v1 = Vector([[1, 0, -5, 2, -8]])
#v1 = Vector([[-8]])
scalar = -0.5
print("\n## Example 18.right")
print(f"shape scalar / m1 = {(scalar / m1).shape}\n", scalar / m1)

## Example 18.left
m1 = Vector([[1, 0, -5, 2, -8]])
scalar = -0.5
print("\n## Example 18.left")
print(f"shape m1 / scalar = {(m1 / scalar).shape}\n", m1 / scalar)

In [1]:
from ex00.matrix import Vector, Matrix

## Example 19
v1 = Vector([[1, 0, -5, 2, -8]])
print("\n## Example 19")
print(f"shape v1 = {(v1).shape}\n", v1)
print(f"shape v1 = {(v1.T()).shape}\n", v1.T())

## Example 20
v1 = Vector([[1], [0], [-5], [2], [-8]])
print("\n## Example 20")
print(f"shape v1 = {(v1).shape}\n", v1)
print(f"shape v1 = {(v1.T()).shape}\n", v1.T())

## Example 21
#v1 = Vector([[1, 2, 3]])
#v2 = Vector([[1, 2, 3]])
#print("\n## Example 21")
#print(f"shape v1.dot(v2) =  {v1.dot(v2)}")

## Example 22
v1 = Vector([[1], [10], [100], [1000], [10000]])
v2 = Vector([[1], [0], [2], [8], [3]])
print("\n## Example 22")
print(f"shape v1.dot(v2) = {v1.dot(v2)}")

## Example 23
v1 = Vector([[1], [0], [-5]])
m1 = Matrix([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print("\n## Example 23")
print(f"shape m1 * v1 =\n{m1 * v1}")

## Example 24
v1 = Vector([[1, 0, -5]])
m1 = Matrix([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print("\n## Example 24")
print(f"shape v1 * m1 =\n{v1 * m1}")


## Example 19
shape v1 = (1, 5)
 Vector([[1, 0, -5, 2, -8]])
shape v1 = (5, 1)
 Vector([[1] [0] [-5] [2] [-8]])

## Example 20
shape v1 = (5, 1)
 Vector([[1] [0] [-5] [2] [-8]])
shape v1 = (1, 5)
 Vector([[1, 0, -5, 2, -8]])

## Example 22
shape v1.dot(v2) = 38201

## Example 23
shape m1 * v1 =
Vector([[-4] [-8] [-12]])

## Example 24
shape v1 * m1 =
Vector([[-14, -14, -14]])


### Pour plus de test, utiliser le fichier test.py

## Exercise 01: TinyStatistician
```python
data = [2, 37, 69, 318, 32, 3, 65, 74, 38, 26, 1 ,79]

print(f"{len(data) = }")
# Output: len(data) = 12

print(f"{(len(data) / 2) % 2 == 0}")
# Output: True

quartile = tstat.quartile(data)

print(f"{quartile[0] = }")
# Output: quartile[0] = 3

print(f"{quartile[1] = }")
# Output: quartile[1] = 69


print(f"{tstat.percentile(data, 2) = }")
# Output: tstat.percentile(data, 2) = 1

print(f"{tstat.percentile(data, 28) = }")
# Output: tstat.percentile(data, 28) = 26

print(f"{tstat.percentile(data, 83) = }")
# Output: tstat.percentile(data, 83) = 74
```

In [ ]:
import math
from ex01.TinyStatistician import TinyStatistician

ts = TinyStatistician()
a = [1, 42, 300, 10, 59]
#a = [2, 37, 69, 318, 32, 3, 65, 74, 38, 26, 1 ,79]

print("mean = ", ts.mean(a))
print("median = ", ts.median(a))
print("quartile = ", ts.quartile(a))
print("percentile(10) = ", ts.percentile(a, 10))
print("percentile(28) = ", ts.percentile(a, 28))
print("percentile(83) = ", ts.percentile(a, 83))
print("var = ", ts.var(a))
print("std = ", ts.std(a))

In [ ]:
import ex01.TinyStatistician as ts

tstat = ts.TinyStatistician()
data = [42, 7, 69, 18, 352, 3, 650, 754, 438, 2659]

print(tstat.mean(data))
print(tstat.median(data))
print(tstat.quartile(data))
print(tstat.percentile(data, 10))
print(tstat.percentile(data, 28))
print(tstat.percentile(data, 83))
print(tstat.var(data))
print(tstat.std(data))

## Exercise 02: Simple prediction

In [ ]:
from ex02.prediction import simple_predict

x = np.arange(1,6).reshape(-1, 1)

# Example 1:
theta1 = np.array([[5],[0]])
pred1 = simple_predict(x, theta1)
print("## Prediction 1:\n", f"type = {type(pred1)}\n", pred1, "\n")
# Ouput:
#array([[5.],[5.],[5.],[5.],[5.]])
# Do you understand why y_hat contains only 5’s here?

# Example 2:
theta2 = np.array([[0],[1]])
pred2 = simple_predict(x, theta2)
print("## Prediction 2:\n", f"type = {type(pred2)}\n", pred2, "\n")
# Output:
#array([[1.],[2.],[3.],[4.],[5.]])
# Do you understand why y_hat == x here?
# Example 3:

theta3 = np.array([[5],[3]])
pred3 = simple_predict(x, theta3)
print("## Prediction 3:\n", f"type = {type(pred3)}\n", pred3, "\n")
# Output:
#array([[ 8.],[11.],[14.],[17.],[20.]])

# Example 4:
theta4 = np.array([[-3],[1]])
pred4 = simple_predict(x, theta4)
print("## Prediction 4:\n", f"type = {type(pred4)}\n", pred4, "\n")
# Output:
#array([[-2.],[-1.],[ 0.],[ 1.],[ 2.]])

## Exercise 03: Add intercept

In [ ]:
from ex03.tools import add_intercept

# Example 1:
x = np.arange(1,6).reshape((5,1))
add_intercept1 = add_intercept(x)
print("## Exemple 1:\n", f"type = {type(add_intercept1)}\n", add_intercept1, "\n")
# Output:
#array([[1., 1.],
#       [1., 2.],
#       [1., 3.],
#       [1., 4.],
#       [1., 5.]])


# Example 2:
y = np.arange(1,10).reshape((3,3))
add_intercept2 = add_intercept(y)
print("## Exemple 2:\n", f"type = {type(add_intercept2)}\n", add_intercept2, "\n")
# Output:
#array([[1., 1., 2., 3.],
#       [1., 4., 5., 6.],
#       [1., 7., 8., 9.]])

## Exercise 04: Prediction

In [ ]:
from ex04.prediction import predict_
import numpy as np

x = np.arange(1,6).reshape(-1, 1)

# Example 1:
theta1 = np.array([[5],[0]])
pred_1 = predict_(x, theta1)
print("## Exemple 1:\n", f"type {type(pred1)}\n", pred1, "\n")
# Ouput:
# array([[5.],[5.],[5.],[5.],[5.]])
# Do you remember why y_hat contains only 5’s here?

# Example 2:
theta2 = np.array([[0],[1]])
pred = predict_(x, theta2)
print("## Exemple 2:\n", f"type {type(pred2)}\n", pred2, "\n")
# Output:
# array([[1.],[2.],[3.],[4.],[5.]])
# Do you remember why y_hat == x here?

# Example 3:
theta3 = np.array([[5],[3]])
pred3 = predict_(x, theta3)
print("## Exemple 3:\n", f"type {type(pred3)}\n", pred3, "\n")
# Output:
# array([[ 8.],[11.],[14.],[17.],[20.]])

# Example 4:
theta4 = np.array([[-3],[1]])
pred4 = predict_(x, theta4)
print("## Exemple 4:\n", f"type {type(pred4)}\n", pred4, "\n")
# Output:
# array([[-2.],[-1.],[ 0.],[ 1.],[ 2.]])

## Exercise 05: Let's Make Nice Plots

In [ ]:
import matplotlib.pyplot as plt
from ex05.plot import plot
plt.ion()

x = np.arange(1,6).reshape(-1, 1)
y = np.array([[3.74013816],[3.61473236],[4.57655287],[4.66793434],[5.95585554]])
    
# Example 1:
theta1 = np.array([[4.5],[-0.2]])
plot(x, y, theta1)
    
# Example 2:
theta2 = np.array([[-1.5],[2]])
plot(x, y, theta2)
    
# Example 3:
theta3 = np.array([[3],[0.3]])
plot(x, y, theta3)

## Exercise 06: loss function

In [ ]:
from ex06.loss import loss_, loss_elem_
from ex04.prediction import predict_

# Example 1:
x1 = np.array([[0.], [1.], [2.], [3.], [4.]])
theta1 = np.array([[2.], [4.]])
y_hat1 = predict_(x1, theta1)

y1 = np.array([[2.], [7.], [12.], [17.], [22.]])
res1 = loss_elem_(y1, y_hat1)
# Output:
#array([[0.], [1], [4], [9], [16]])
expected_res1 = np.array([[0.], [1], [4], [9], [16]])

# Example 2:
res2 =  loss_(y1, y_hat1)
# Output:
# 3.0
expected_res2 = 3.0

# Example 3:
x2 = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
theta2 = np.array([[0.05], [1.], [1.], [1.]])
y_hat2 = predict_(x2, theta2)
y2 = np.array([[19.], [42.], [67.], [93.]])

res3 = loss_elem_(y2, y_hat2)
# Output:
# array([[10.5625], [6.0025], [0.1225], [17.2225]])
expected_res3 = np.array([[10.5625], [6.0025], [0.1225], [17.2225]])

# Example 4:
res4 = loss_(y2, y_hat2)
# Output:
# 4.238750000000004
expected_res4 = 4.238750000000004


# Example 5:
x3 = np.array([[0],[ 15],[ -9],[ 7],[ 12],[ 3],[ -21]])
theta3 = np.array([[0.], [1.]])
y_hat3 = predict_(x3, theta3)
y3 = np.array([[2],[ 14],[ -13],[ 5],[ 12],[ 4],[ -19]])

res5 = loss_(y3, y_hat3)
# Output:
# 2.142857142857143
expected_res5 = 2.142857142857143

# Example 6:
res6 = loss_(y3, y3)
# Output:
# 0.0
expected_res6 = 0.0

res = [res1, res2, res3, res4, res5, res6]
expected_res = [expected_res1, expected_res2, expected_res3, expected_res4, expected_res5, expected_res6]

ii = 0
for p, q in zip(res, expected_res):
    print(f"Exemple {ii} ======================")
    print(f"result: \n{p}\nExpected result: \n{q}\n\n")
    ii += 1

## Exercise 07: Vectorized loss function

In [ ]:
from ex07.vec_loss import loss_

X = np.array([[0],[ 15],[ -9],[ 7],[ 12],[ 3],[ -21]])
Y = np.array([[2],[ 14],[ -13],[ 5],[ 12],[ 4],[ -19]])
# Example 1:
print(f"Example 1: {loss_(X, Y)}".ljust(40) + f"type = {type(loss_(X, Y))}")
# Output:
#2.142857142857143


# Example 2:
print(f"Example 2: {loss_(X, X)}".ljust(40) + f"type = {type(loss_(X, X))}")
# Output:
#0.0

## Exercise 08: Lets Make Plots Again

In [ ]:
from ex08.plot import plot_with_loss
import matplotlib.pyplot as plt
plt.ion()

x = np.arange(1,6).reshape(-1,1)
y = np.array([[11.52434424], [10.62589482], [13.14755699], [18.60682298], [14.14329568]])
#Example 1:
theta1= np.array([[18],[-1]])
plot_with_loss(x, y, theta1)
# Output:
#Example 2:
theta2 = np.array([[14], [0]])
plot_with_loss(x, y, theta2)
# Output:
#Example 3:
theta3 = np.array([[12], [0.8]])
plot_with_loss(x, y, theta3)

## Exercise 09: Other loss functions

In [ ]:
from ex09.other_losses import mse_, rmse_, mae_, r2score_
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from math import sqrt

x = np.array([[0],[ 30],[ -9],[ 7],[ 12],[ 3],[ -21]])
y = np.array([[2],[ 14],[ -13],[ 5],[ 12],[ 4],[ -19]])

# Mean squared error
## your implementation
res = mse_(x,y)
## Output:
## 4.285714285714286
## sklearn implementation
expect_res = mean_squared_error(x,y)
## Output:
## 4.285714285714286
print(f"## MSE =========")
print("result =".ljust(30), res, "\nexpected_result =".ljust(30), expect_res)

# Root mean squared error
## your implementation
res = rmse_(x,y)
## Output:
## 2.0701966780270626
## sklearn implementation not available: take the square root of MSE
expect_res = sqrt(mean_squared_error(x,y))
## Output:
## 2.0701966780270626
print(f"## RMSE =========")
print("result =".ljust(30), res, "\nexpected_result =".ljust(30), expect_res)

# Mean absolute error
## your implementation
res = mae_(x,y)
# Output:
## 1.7142857142857142
## sklearn implementation
expect_res = mean_absolute_error(x,y)
# Output:
## 1.7142857142857142
print(f"## MAE =========")
print("result =".ljust(30), res, "\nexpected_result =".ljust(30), expect_res)

# R2-score
## your implementation
res = r2score_(x,y)
## Output:
## 0.9681721733858745
## sklearn implementation
expect_res = r2_score(x,y)
## Output:
## 0.9681721733858745
print(f"## R2Score =========")
print("result =".ljust(30), res, "\nexpected_result =".ljust(30), expect_res)