In [1]:
import numpy as np

# Module 00: Stepping into Machine Learning

## Exercise 00: Matrix

In [4]:
from ex00.matrix import Matrix

# Instance
m1 = Matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(f"shape = {m1.shape}\n", m1)
m2 = Matrix([[0],[1],[2]])
print(f"shape = {m2.shape}\n", m2)
m3 = Matrix([[1, 2, 3, 11, 12, 13, 21, 22, 23, 31, 32, 33],[4, 5, 6, 14, 15, 16, 24, 25, 26, 34, 35, 36]])
print(f"shape = {m3.shape}\n", m3)

m4 = Matrix((1, 1))
print(f"shape = {m4.shape}\n", m4)
m5 = Matrix((2, 3))
print(f"shape = {m5.shape}\n", m5)
m6 = Matrix((1, 10))
print(f"shape = {m6.shape}\n", m6)
m7 = Matrix((10, 1))
print(f"shape = {m7.shape}\n", m7)

# Addition matrice avec matrice, float, str, tuple, list
m1 = Matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
m2 = Matrix([[9, 8, 7],[6, 5, 4],[3, 2, 1]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)

m1 = Matrix([[1],[4],[7]])
m2 = Matrix([[7],[5],[3]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)

m1 = Matrix([[1, 2, 3]])
m2 = Matrix([[3, 4, 5]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)

m1 = Matrix([[1]])
m2 = Matrix([[3]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)

m1 = Matrix([[1, 0, -5, 2, -8], [1, 0, -5, 2, -8]])
m2 = Matrix([[1.01, 0.8, -1.25, 2.5, -3.1], [3, -1.2, -2.5, 1, -4]])
print(f"shape m1 +m2 = {(m1 + m2).shape}\n", m1 + m2)




shape = (3, 3)
 Matrix([[1, 2, 3] [4, 5, 6] [7, 8, 9]])
shape = (3, 1)
 Matrix([[0] [1] [2]])
shape = (2, 12)
 Matrix([[1, 2, 3, 11, 12, 13, 21, 22, 23, 31, 32, 33] [4, 5, 6, 14, 15, 16, 24, 25, 26, 34, 35, 36]])
shape = (1, 1)
 Matrix([[0]])
shape = (2, 3)
 Matrix([[0, 0, 0] [0, 0, 0]])
shape = (1, 10)
 Matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
shape = (10, 1)
 Matrix([[0] [0] [0] [0] [0] [0] [0] [0] [0] [0]])
shape m1 +m2 = (3, 3)
 Matrix([[10, 10, 10] [10, 10, 10] [10, 10, 10]])
shape m1 +m2 = (3, 1)
 Matrix([[8] [9] [10]])
shape m1 +m2 = (1, 3)
 Matrix([[4, 6, 8]])
shape m1 +m2 = (1, 1)
 Matrix([[4]])
shape m1 +m2 = (2, 5)
 Matrix([[2.01, 0.8, -6.25, 4.5, -11.1] [4, -1.2, -7.5, 3, -12]])


## Exercise 01: TinyStatistician
```python
data = [2, 37, 69, 318, 32, 3, 65, 74, 38, 26, 1 ,79]

print(f"{len(data) = }")
# Output: len(data) = 12

print(f"{(len(data) / 2) % 2 == 0}")
# Output: True

quartile = tstat.quartile(data)

print(f"{quartile[0] = }")
# Output: quartile[0] = 3

print(f"{quartile[1] = }")
# Output: quartile[1] = 69


print(f"{tstat.percentile(data, 2) = }")
# Output: tstat.percentile(data, 2) = 1

print(f"{tstat.percentile(data, 28) = }")
# Output: tstat.percentile(data, 28) = 26

print(f"{tstat.percentile(data, 83) = }")
# Output: tstat.percentile(data, 83) = 74
```

In [15]:
import math
from ex01.TinyStatistician import TinyStatistician

ts = TinyStatistician()
a = [1, 42, 300, 10, 59]
#a = [2, 37, 69, 318, 32, 3, 65, 74, 38, 26, 1 ,79]

print("mean = ", ts.mean(a))
print("median = ", ts.median(a))
print("quartile = ", ts.quartile(a))
print("percentile(10) = ", ts.percentile(a, 10))
print("percentile(28) = ", ts.percentile(a, 28))
print("percentile(83) = ", ts.percentile(a, 83))
print("var = ", ts.var(a))
print("std = ", ts.std(a))

mean =  82.4
median =  42
quartile =  [10, 59]
percentile(10) =  1
percentile(28) =  10
percentile(83) =  300
var =  12279.439999999999
std =  110.81263465868862


In [16]:
import ex01.TinyStatistician as ts

tstat = ts.TinyStatistician()
data = [42, 7, 69, 18, 352, 3, 650, 754, 438, 2659]

print(tstat.mean(data))
print(tstat.median(data))
print(tstat.quartile(data))
print(tstat.percentile(data, 10))
print(tstat.percentile(data, 28))
print(tstat.percentile(data, 83))
print(tstat.var(data))
print(tstat.std(data))

499.2
210.5
[18, 650]
3
18
754
589194.56
767.5900989460456


## Exercise 02: Simple prediction

In [3]:
from ex02.prediction import simple_predict

x = np.arange(1,6).reshape(-1, 1)

# Example 1:
theta1 = np.array([[5],[0]])
print(simple_predict(x, theta1), "\n")
# Ouput:
#array([[5.],[5.],[5.],[5.],[5.]])
# Do you understand why y_hat contains only 5’s here?

# Example 2:
theta2 = np.array([[0],[1]])
print(simple_predict(x, theta2), "\n")
# Output:
#array([[1.],[2.],[3.],[4.],[5.]])
# Do you understand why y_hat == x here?
# Example 3:

theta3 = np.array([[5],[3]])
print(simple_predict(x, theta3), "\n")
# Output:
#array([[ 8.],[11.],[14.],[17.],[20.]])

# Example 4:
theta4 = np.array([[-3],[1]])
print(simple_predict(x, theta4), "\n")
# Output:
#array([[-2.],[-1.],[ 0.],[ 1.],[ 2.]])

[[5.]
 [5.]
 [5.]
 [5.]
 [5.]] 

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]] 

[[ 8.]
 [11.]
 [14.]
 [17.]
 [20.]] 

[[-2.]
 [-1.]
 [ 0.]
 [ 1.]
 [ 2.]] 



## Exercise 03: Add intercept

In [3]:
from ex03.tools import add_intercept

# Example 1:
x = np.arange(1,6).reshape((5,1))
print(add_intercept(x), "\n")
# Output:
#array([[1., 1.],
#       [1., 2.],
#       [1., 3.],
#       [1., 4.],
#       [1., 5.]])


# Example 2:
y = np.arange(1,10).reshape((3,3))
print(add_intercept(y))
# Output:
#array([[1., 1., 2., 3.],
#       [1., 4., 5., 6.],
#       [1., 7., 8., 9.]])

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]] 

[[1. 1. 2. 3.]
 [1. 4. 5. 6.]
 [1. 7. 8. 9.]]


## Exercise 04: Prediction

In [2]:
from ex04.prediction import predict_
import numpy as np

x = np.arange(1,6).reshape(-1, 1)

# Example 1:
theta1 = np.array([[5],[0]])
print(predict_(x, theta1), "\n")
# Ouput:
# array([[5.],[5.],[5.],[5.],[5.]])
# Do you remember why y_hat contains only 5’s here?

# Example 2:
theta2 = np.array([[0],[1]])
print(predict_(x, theta2), "\n")
# Output:
# array([[1.],[2.],[3.],[4.],[5.]])
# Do you remember why y_hat == x here?

# Example 3:
theta3 = np.array([[5],[3]])
print(predict_(x, theta3), "\n")
# Output:
# array([[ 8.],[11.],[14.],[17.],[20.]])

# Example 4:
theta4 = np.array([[-3],[1]])
print(predict_(x, theta4), "\n")
# Output:
# array([[-2.],[-1.],[ 0.],[ 1.],[ 2.]])

## Exercise 05: Let's Make Nice Plots

In [ ]:
#from ex05.plot import ...

## Exercise 06: loss function

In [ ]:
#from ex06.loss import ...

## Exercise 07: Vectorized loss function

In [ ]:
#from ex07.vec_loss import ...

## Exercise 08: Lets Make Plots Again

In [ ]:
#from ex08.plot import ...

## Exercise 09: Other loss functions

In [ ]:
#from ex09.other_losses import ...